update yml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,8 +34,19 @@ jobs:
       - name: Increment version
         id: bump-version
         run: |
+          set -e
+          echo "Reading current version from app.json"
           current_version=$(jq -r '.expo.version' app.json)
+          if [ -z "$current_version" ]; then
+            echo "Failed to read current version from app.json"
+            exit 1
+          fi
+          echo "Current version: $current_version"
           IFS='.' read -r -a version_parts <<< "$current_version"
+          if [ ${#version_parts[@]} -ne 3 ]; then
+            echo "Version format is incorrect. Expected format: x.y.z"
+            exit 1
+          fi
           ((version_parts[2]++))
           new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
           echo "New version: $new_version"
@@ -97,7 +108,7 @@ jobs:
         env:
           EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
         run: |
-          eas submit --platform ios --latest --non-interactive || {
+          eas submit --platform --latest --non-interactive || {
             cat .eas/eas.log;
             exit 1;
           }
